const actionTypes={
    LOAD_COIN_SUCCESS:'LOAD_COIN_SUCCESS',
    LOAD_EXCHANGE_SUCCESS:'LOAD_EXCHANGE_SUCCESS',
    SAVE_COIN_SUCCESS:'SAVE_COIN_SUCCESS',
    SAVE_EXCHANGE_SUCCESS:'SAVE_EXCHANGE_SUCCESS'
    
};
export default actionTypes;